<a href="https://colab.research.google.com/github/SUCCESSneeded/numpy-100/blob/master/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

How to Add a Border Around a NumPy Array?

In [17]:
'''| Mode          | Meaning                         | Example                       |
| ------------- | ------------------------------- | ----------------------------- |
| `constant`    | Adds a fixed value              | `[1,2,3] → [0,1,2,3,0]`       |
| `edge`        | Repeats edge values             | `[1,2,3] → [1,1,2,3,3]`       |
| `linear_ramp` | Adds values in a linear ramp    | gradually increases/decreases |
| `maximum`     | Pads using maximum value        | `[1,2,3] → [3,1,2,3,3]`       |
| `minimum`     | Pads using minimum value        | `[1,2,3] → [1,1,2,3,1]`       |
| `mean`        | Pads using mean                 | mean of array/edge            |
| `median`      | Pads using median               | median of array/edge          |
| `wrap`        | Wraps values from opposite side | `[1,2,3] → [3,1,2,3,1]`       |
| `symmetric`   | Mirrors values including edge   | `[1,2,3] → [2,1,2,3,2]`       |
| `reflect`     | Mirrors values excluding edge   | `[1,2,3] → [2,1,2,3,2]`       |
'''

'| Mode          | Meaning                         | Example                       |\n| ------------- | ------------------------------- | ----------------------------- |\n| `constant`    | Adds a fixed value              | `[1,2,3] → [0,1,2,3,0]`       |\n| `edge`        | Repeats edge values             | `[1,2,3] → [1,1,2,3,3]`       |\n| `linear_ramp` | Adds values in a linear ramp    | gradually increases/decreases |\n| `maximum`     | Pads using maximum value        | `[1,2,3] → [3,1,2,3,3]`       |\n| `minimum`     | Pads using minimum value        | `[1,2,3] → [1,1,2,3,1]`       |\n| `mean`        | Pads using mean                 | mean of array/edge            |\n| `median`      | Pads using median               | median of array/edge          |\n| `wrap`        | Wraps values from opposite side | `[1,2,3] → [3,1,2,3,1]`       |\n| `symmetric`   | Mirrors values including edge   | `[1,2,3] → [2,1,2,3,2]`       |\n| `reflect`     | Mirrors values excluding edge   | `[1,2,3] → [

In [18]:
#USING numpy.pad(array, pad_width, mode='constant', constant_values=value)


In [19]:
#border of -1 around a 4×1 column vector.
arr=np.array([[10],[20],[30],[40]])
padded=np.pad(arr,pad_width=1,mode="constant",constant_values=-1)
print(arr)
print(padded)

[[10]
 [20]
 [30]
 [40]]
[[-1 -1 -1]
 [-1 10 -1]
 [-1 20 -1]
 [-1 30 -1]
 [-1 40 -1]
 [-1 -1 -1]]


In [21]:
#a border is added around a 2×2 array. A padding width of 1 and a border value of 0 are used to surround the original matrix.

arr=np.zeros((2,3))
padded2=np.pad(arr,pad_width=1,mode="constant",constant_values=1)
print(arr)
print(padded2)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
#pads only the top and bottom of an array by using different padding widths for each side.
arr = np.arange(6).reshape(2, 3)
out = np.pad(arr, pad_width=((1, 1), (0, 0)), mode="constant", constant_values=9)
print(out)

[[9 9 9]
 [0 1 2]
 [3 4 5]
 [9 9 9]]


# How to compare two NumPy arrays?

In [28]:
# np.array_equal(arr1,arr2)
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr2)
is_equal=np.array_equal(arr1,arr2)
print(is_equal)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
True


True

In [32]:
#Using == and .all()
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

dif = arr1 == arr2
b = dif.all()
print(dif)
print(b)

[[ True  True]
 [ True  True]]
True


In [33]:
#code compares two arrays element by element using greater/less operators.
a = np.array([101, 99, 87])
b = np.array([897, 97, 111])

print("Array a:", a)
print("Array b:", b)

print("a > b:",np.greater(a,b))
print("a >= b:",np.greater_equal(a,b))
print("a < b:",np.less(a,b))
print("a <= b:",np.less_equal(a,b))

Array a: [101  99  87]
Array b: [897  97 111]
a > b: [False  True False]
a >= b: [False  True False]
a < b: [ True False  True]
a <= b: [ True False  True]


#How to Check Whether Specified Values are Present in NumPy Array?

In [36]:
#using NumPy's Vectorized Comparison
arr = np.array([[2, 3, 0],
                [4, 1, 6]])
val=6
p=np.any(arr==val)
print(p)

True


In [41]:
#Using NumPy isin() for Multiple Values
arr = np.array([[2, 3, 0],
                [4, 1, 6]])
vals=[0,4,60]
ans={v:bool(np.isin(v,arr)) for v in vals}
print(ans)

{0: True, 4: True, 60: False}


In [42]:
#Using in Operator
arr = np.array([[2, 3, 0],
                [4, 1, 6]])

print(2 in arr)
print(10 in arr)

True
False


In [45]:
#Using Flattening and Python Membership
arr = np.array([[2, 3, 0],
                [4, 1, 6]])
v=3
out=v in arr.ravel() # flattening array
print(out)

True
