<a href="https://colab.research.google.com/github/SUCCESSneeded/numpy-100/blob/master/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

How to Add a Border Around a NumPy Array?

In [2]:
'''| Mode          | Meaning                         | Example                       |
| ------------- | ------------------------------- | ----------------------------- |
| `constant`    | Adds a fixed value              | `[1,2,3] → [0,1,2,3,0]`       |
| `edge`        | Repeats edge values             | `[1,2,3] → [1,1,2,3,3]`       |
| `linear_ramp` | Adds values in a linear ramp    | gradually increases/decreases |
| `maximum`     | Pads using maximum value        | `[1,2,3] → [3,1,2,3,3]`       |
| `minimum`     | Pads using minimum value        | `[1,2,3] → [1,1,2,3,1]`       |
| `mean`        | Pads using mean                 | mean of array/edge            |
| `median`      | Pads using median               | median of array/edge          |
| `wrap`        | Wraps values from opposite side | `[1,2,3] → [3,1,2,3,1]`       |
| `symmetric`   | Mirrors values including edge   | `[1,2,3] → [2,1,2,3,2]`       |
| `reflect`     | Mirrors values excluding edge   | `[1,2,3] → [2,1,2,3,2]`       |
'''

'| Mode          | Meaning                         | Example                       |\n| ------------- | ------------------------------- | ----------------------------- |\n| `constant`    | Adds a fixed value              | `[1,2,3] → [0,1,2,3,0]`       |\n| `edge`        | Repeats edge values             | `[1,2,3] → [1,1,2,3,3]`       |\n| `linear_ramp` | Adds values in a linear ramp    | gradually increases/decreases |\n| `maximum`     | Pads using maximum value        | `[1,2,3] → [3,1,2,3,3]`       |\n| `minimum`     | Pads using minimum value        | `[1,2,3] → [1,1,2,3,1]`       |\n| `mean`        | Pads using mean                 | mean of array/edge            |\n| `median`      | Pads using median               | median of array/edge          |\n| `wrap`        | Wraps values from opposite side | `[1,2,3] → [3,1,2,3,1]`       |\n| `symmetric`   | Mirrors values including edge   | `[1,2,3] → [2,1,2,3,2]`       |\n| `reflect`     | Mirrors values excluding edge   | `[1,2,3] → [

In [3]:
#USING numpy.pad(array, pad_width, mode='constant', constant_values=value)


In [4]:
#border of -1 around a 4×1 column vector.
arr=np.array([[10],[20],[30],[40]])
padded=np.pad(arr,pad_width=1,mode="constant",constant_values=-1)
print(arr)
print(padded)

[[10]
 [20]
 [30]
 [40]]
[[-1 -1 -1]
 [-1 10 -1]
 [-1 20 -1]
 [-1 30 -1]
 [-1 40 -1]
 [-1 -1 -1]]


In [5]:
#a border is added around a 2×2 array. A padding width of 1 and a border value of 0 are used to surround the original matrix.

arr=np.zeros((2,3))
padded2=np.pad(arr,pad_width=1,mode="constant",constant_values=1)
print(arr)
print(padded2)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
#pads only the top and bottom of an array by using different padding widths for each side.
arr = np.arange(6).reshape(2, 3)
out = np.pad(arr, pad_width=((1, 1), (0, 0)), mode="constant", constant_values=9)
print(out)

[[9 9 9]
 [0 1 2]
 [3 4 5]
 [9 9 9]]


# How to compare two NumPy arrays?

In [7]:
# np.array_equal(arr1,arr2)
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr2)
is_equal=np.array_equal(arr1,arr2)
print(is_equal)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
True


In [8]:
#Using == and .all()
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

dif = arr1 == arr2
b = dif.all()
print(dif)
print(b)

[[ True  True]
 [ True  True]]
True


In [9]:
#code compares two arrays element by element using greater/less operators.
a = np.array([101, 99, 87])
b = np.array([897, 97, 111])

print("Array a:", a)
print("Array b:", b)

print("a > b:",np.greater(a,b))
print("a >= b:",np.greater_equal(a,b))
print("a < b:",np.less(a,b))
print("a <= b:",np.less_equal(a,b))

Array a: [101  99  87]
Array b: [897  97 111]
a > b: [False  True False]
a >= b: [False  True False]
a < b: [ True False  True]
a <= b: [ True False  True]


#How to Check Whether Specified Values are Present in NumPy Array?

In [10]:
#using NumPy's Vectorized Comparison
arr = np.array([[2, 3, 0],
                [4, 1, 6]])
val=7
p=np.any(arr==val)
print(p)

False


In [11]:
#Using NumPy isin() for Multiple Values
arr = np.array([[2, 3, 0],
                [4, 1, 6]])
vals=[0,4,60]
ans={v:bool(np.isin(v,arr)) for v in vals}
print(ans)

{0: True, 4: True, 60: False}


In [12]:
#Using in Operator
arr = np.array([[2, 3, 0],
                [4, 1, 6]])

print(2 in arr)
print(10 in arr)

True
False


In [13]:
#Using Flattening and Python Membership
arr = np.array([[2, 3, 0],
                [4, 1, 6]])
v=3
out=v in arr.ravel() # flattening array
print(out)

True


How to get all 2D diagonals of a 3D NumPy array

In [14]:
#you can extract 2D diagonals from each sub-array of a
#3D array using numpy.diagonal() function.

#np.diagonal(a, axis1, axis2)
# Create a 3D numpy array of shape (3, 4, 4)
arr = np.arange(3 * 4 * 4).reshape(3, 4, 4)
print("Original 3D array:\n", arr)

# Extract diagonals from each 2D sub-array
diag_arr = np.diagonal(arr, axis1=1, axis2=2)
print("\n2D diagonal array:\n", diag_arr)

Original 3D array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]

2D diagonal array:
 [[ 0  5 10 15]
 [16 21 26 31]
 [32 37 42 47]]


FLATTEN A MATRIX

In [15]:
matrix = np.array([[10, 20, 30], [40, 50, 60]])
flat = matrix.flatten(order='F')
print(flat)

'''Parameters:
order='C' Flatten in row-major order (default).
order='F' Flatten in column-major order.
order='A' Flatten in column-major if memory is Fortran-contiguous, else row-major.
order='K' Flatten in the order elements occur in memory.
'''

[10 40 20 50 30 60]


"Parameters:\norder='C' Flatten in row-major order (default).\norder='F' Flatten in column-major order.\norder='A' Flatten in column-major if memory is Fortran-contiguous, else row-major.\norder='K' Flatten in the order elements occur in memory.\n"

Flatten a 2D Numpy Array into 1D Array

In [16]:
#USING NP.RAVEL()
a = np.array([[1, 2, 3], [4, 5, 6]])
res = a.ravel()
print(res)

[1 2 3 4 5 6]


In [17]:
#Using np.ndarray.flatten()
a = np.array([[1, 2, 3], [4, 5, 6]])
res = a.flatten()
print(res)

[1 2 3 4 5 6]


In [18]:
#using reshape(-1)-> coverts array in 1 d
#The -1 tells NumPy to automatically compute the required length.
a = np.array([[1, 2, 3], [4, 5, 6]])
res = a.reshape(-1)
print(res)

[1 2 3 4 5 6]


In [19]:
#using concatenate-> it convat each array one by one forming 1D array
res=np.concatenate(a)
print(res)

[1 2 3 4 5 6]


REVERSE AN ARRAY

In [20]:
#USING SLICING
#USING NP.FLIP()
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
res1=np.flip(arr)

print(res1)
for r in res1:
  for i in range(len(r)//2):
    r[i],r[arr.shape[1]-1-i]=r[arr.shape[1]-1-i],r[i]

print(res1)


[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


To rearrange axes of an array.

In [21]:
#numpy.moveaxis(array, source, destination)
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr)

arr2=np.moveaxis(arr,0,2)
print(arr2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [22]:
result = np.moveaxis(arr, source=[0,1], destination=[1,2])
result


array([[[1, 3],
        [5, 7]],

       [[2, 4],
        [6, 8]]])

In [23]:
result = np.moveaxis(arr, source=[0], destination=[1])
result

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

INTERCHNAGE THE AXES OF ARRAY

In [24]:
#np.swapaxes(arr, axis1, axis2)
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr)
print(np.swapaxes(arr,0,2))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]


In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

result = np.swapaxes(arr, axis1=0, axis2=1)
result

array([[1, 4],
       [2, 5],
       [3, 6]])

Fibonacci Series using Binet Formula

In [26]:
import numpy as np

# We are creating an array contains n = 10 elements
# for getting first 10 Fibonacci numbers
a = np.arange(1, 11)
lengthA = len(a)

# splitting of terms for easiness
sqrtFive = np.sqrt(5)
alpha = (1 + sqrtFive) / 2
beta = (1 - sqrtFive) / 2

# Implementation of formula
# np.rint is used for rounding off to integer
Fn = np.rint(((alpha ** a) - (beta ** a)) / (sqrtFive))
print("The first {} numbers of Fibonacci series are {} . ".format(lengthA, Fn))

The first 10 numbers of Fibonacci series are [ 1.  1.  2.  3.  5.  8. 13. 21. 34. 55.] . 


COUNT NONZERO

In [27]:
#numpy.count_nonzero(arr, axis=None)
arr = [[0, 1, 2, 3, 0],
       [0, 5, 6, 0, 7]]
result = np.count_nonzero(arr)
result

6

COUNT THE NO.OF ELEMENTS

In [28]:
#numpy.size(arr, axis=None)
'''total count of all elements, or to count elements along a specific axis.'''

'total count of all elements, or to count elements along a specific axis.'

In [29]:
#TO COUNT total number of elements
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(np.size(arr))

8


In [30]:
#to count elements along specific axis
print(np.size(arr, 0))
print(np.size(arr, 1))

2
4


TRIM LEADING ZEROS

In [31]:
#numpy.trim_zeros(filt, trim='fb')
# removes the leading and trailing zeros from a 1-D array.

In [32]:
a = np.array([0, 0, 3, 4, 0, 5, 0, 0])
res = np.trim_zeros(a)
print(res)

[3 4 0 5]


CHANGE THE DTYE OF AN ARRAY

In [33]:
#Syntax: ndarray.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)

How to make a NumPy array read-only?

In [34]:
import numpy as np


a = np.zeros(11)
print("Before any change ")
print(a)

a[1] = 2
print("Before after first change ")
print(a)

a.setflags(write=False)
print("After making array immutable on attempting  second change ")
#SETflags is used for changing properties from mutable to immutable

Before any change 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Before after first change 
[0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After making array immutable on attempting  second change 


MAX in matrix

In [35]:
m = np.matrix('[64, 1; 12, 3]') # .matrix is restricted till 2D only
print(m)
mx = m.max()
print(mx)

[[64  1]
 [12  3]]
64


SIZE OF ROWS AND COLUMNS

In [36]:
m = np.array([[9, 9, 9], [8, 8, 8]])
rows, cols = m.shape
print(rows,cols)

2 3


SELECT ELEMENTS FROM THE GIVEN MATRIX.

In [37]:
#matrix.take(index, axis)
# IT RETURNS MATRIX OF SELECTED INDEXES
# import the important module in python

# make matrix with numpy
gfg = np.matrix('[4, 1, 12, 3, 4, 6, 7]')

# applying matrix.take() method
geek = gfg.take(2)

print(geek)

[[12]]


FIND SUM OF ELMENTS IN MAT

In [38]:
#matrix.sum(axis=None)

In [39]:
m = np.matrix([[4, 1, 9],
               [12, 3, 1],
               [4, 5, 6]])
out = m.sum(axis=1)
print(out)

[[14]
 [16]
 [15]]


Calculate the sum of the diagonal elements of a NumPy array


In [40]:
#Syntax : numpy.trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None)
'''Sometimes we need to find the sum of the Upper right, Upper left, Lower right, or lower
left diagonal elements. Numpy provides us the facility to compute the sum
of different diagonals elements using numpy.trace() and numpy.diagonal() method.
'''
#offset which diag we have to take
#out=to store the result

'Sometimes we need to find the sum of the Upper right, Upper left, Lower right, or lower\nleft diagonal elements. Numpy provides us the facility to compute the sum\nof different diagonals elements using numpy.trace() and numpy.diagonal() method.\n'

In [41]:
#numpy.diagonal(a, offset=0, axis1=0, axis2=1)

# importing Numpy package
import numpy as np

# creating a 3X3 Numpy matrix
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])

# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)

# Finding the diagonal elements of a matrix
diag = np.diagonal(n_array)

print("\nDiagonal elements are:")
print(diag)

print("\nSum of Diagonal elements is:")
print(sum(diag))

Numpy Matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Diagonal elements are:
[55 44 77]

Sum of Diagonal elements is:
176


Adding and Subtracting Matrices in Python


In [42]:
#np.add() adds two matrices element wise

a=np.array([[1,2],[3,4]])
b=np.array([[6,7],[8,9]])
result=np.add(a,b)
print(a)
print(b)
print(result)
#np.add() for subtraction

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]
[[ 7  9]
 [11 13]]


WAYS TO ADD ROWS AND COLUMNS

In [43]:
# np.append(arr1,arr2,axis)
a=np.array([[43,15,28,183],[12,23,24,57],[44,56,243,78]])
b=np.array([[11,34,57,7]])

x=np.append(a,b,axis=0)
print(x)

[[ 43  15  28 183]
 [ 12  23  24  57]
 [ 44  56 243  78]
 [ 11  34  57   7]]


In [44]:
# np.concatenate((a1,a1,a3....),axis,out=none,dtype=none,casting="same_kind") joins two or more arrays along
# a specified axis.

a = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])
b = np.array([[1],[2],[3]])

x=np.concatenate([a,b],axis=1)
print(x)

[[ 1  2  3  1]
 [45  4  7  2]
 [ 9  6 10  3]]


In [45]:
#np.insert(arr,obj,values,axis=none) inserts values into a NumPy array at specified positions along a given axis.

a = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])
b = np.array([[1],[2],[3]])

x=np.insert(a,1,b.flatten(),axis=1)
print(x)


[[ 1  1  2  3]
 [45  2  4  7]
 [ 9  3  6 10]]


In [46]:
# np.hstack(tuple) horizontally stacks arrays (adds columns side by side).

a = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])
b = np.array([1, 2, 3])

c = np.hstack((a, np.atleast_2d(b).T))  # converts 1D array into 2D array and take transpose
print (c)

[[ 1  2  3  1]
 [45  4  7  2]
 [ 9  6 10  3]]


In [47]:
# np.column_stack() stacks 1D or 2D arrays as columns to form a 2D array.

import numpy as np
a = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])
b = np.array([1, 2, 3])

c = np.column_stack((a, b))
print (c)

[[ 1  2  3  1]
 [45  4  7  2]
 [ 9  6 10  3]]


ADD A ROW IN NUMPY ARRAY.

In [48]:
# np.r_ is a shortcut for stacking arrays vertically (row-wise).

a = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])
b = np.array([1, 2, 3])

c = np.r_[a,[b]]
print (c)

[[ 1  2  3]
 [45  4  7]
 [ 9  6 10]
 [ 1  2  3]]
