<a href="https://colab.research.google.com/github/SUCCESSneeded/numpy-100/blob/master/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

How to Add a Border Around a NumPy Array?

In [3]:
'''| Mode          | Meaning                         | Example                       |
| ------------- | ------------------------------- | ----------------------------- |
| `constant`    | Adds a fixed value              | `[1,2,3] → [0,1,2,3,0]`       |
| `edge`        | Repeats edge values             | `[1,2,3] → [1,1,2,3,3]`       |
| `linear_ramp` | Adds values in a linear ramp    | gradually increases/decreases |
| `maximum`     | Pads using maximum value        | `[1,2,3] → [3,1,2,3,3]`       |
| `minimum`     | Pads using minimum value        | `[1,2,3] → [1,1,2,3,1]`       |
| `mean`        | Pads using mean                 | mean of array/edge            |
| `median`      | Pads using median               | median of array/edge          |
| `wrap`        | Wraps values from opposite side | `[1,2,3] → [3,1,2,3,1]`       |
| `symmetric`   | Mirrors values including edge   | `[1,2,3] → [2,1,2,3,2]`       |
| `reflect`     | Mirrors values excluding edge   | `[1,2,3] → [2,1,2,3,2]`       |
'''

'| Mode          | Meaning                         | Example                       |\n| ------------- | ------------------------------- | ----------------------------- |\n| `constant`    | Adds a fixed value              | `[1,2,3] → [0,1,2,3,0]`       |\n| `edge`        | Repeats edge values             | `[1,2,3] → [1,1,2,3,3]`       |\n| `linear_ramp` | Adds values in a linear ramp    | gradually increases/decreases |\n| `maximum`     | Pads using maximum value        | `[1,2,3] → [3,1,2,3,3]`       |\n| `minimum`     | Pads using minimum value        | `[1,2,3] → [1,1,2,3,1]`       |\n| `mean`        | Pads using mean                 | mean of array/edge            |\n| `median`      | Pads using median               | median of array/edge          |\n| `wrap`        | Wraps values from opposite side | `[1,2,3] → [3,1,2,3,1]`       |\n| `symmetric`   | Mirrors values including edge   | `[1,2,3] → [2,1,2,3,2]`       |\n| `reflect`     | Mirrors values excluding edge   | `[1,2,3] → [

In [4]:
#USING numpy.pad(array, pad_width, mode='constant', constant_values=value)


In [5]:
#border of -1 around a 4×1 column vector.
arr=np.array([[10],[20],[30],[40]])
padded=np.pad(arr,pad_width=1,mode="constant",constant_values=-1)
print(arr)
print(padded)

[[10]
 [20]
 [30]
 [40]]
[[-1 -1 -1]
 [-1 10 -1]
 [-1 20 -1]
 [-1 30 -1]
 [-1 40 -1]
 [-1 -1 -1]]


In [6]:
#a border is added around a 2×2 array. A padding width of 1 and a border value of 0 are used to surround the original matrix.

arr=np.zeros((2,3))
padded2=np.pad(arr,pad_width=1,mode="constant",constant_values=1)
print(arr)
print(padded2)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
#pads only the top and bottom of an array by using different padding widths for each side.
arr = np.arange(6).reshape(2, 3)
out = np.pad(arr, pad_width=((1, 1), (0, 0)), mode="constant", constant_values=9)
print(out)

[[9 9 9]
 [0 1 2]
 [3 4 5]
 [9 9 9]]


# How to compare two NumPy arrays?

In [8]:
# np.array_equal(arr1,arr2)
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr2)
is_equal=np.array_equal(arr1,arr2)
print(is_equal)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
True


In [9]:
#Using == and .all()
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

dif = arr1 == arr2
b = dif.all()
print(dif)
print(b)

[[ True  True]
 [ True  True]]
True


In [10]:
#code compares two arrays element by element using greater/less operators.
a = np.array([101, 99, 87])
b = np.array([897, 97, 111])

print("Array a:", a)
print("Array b:", b)

print("a > b:",np.greater(a,b))
print("a >= b:",np.greater_equal(a,b))
print("a < b:",np.less(a,b))
print("a <= b:",np.less_equal(a,b))

Array a: [101  99  87]
Array b: [897  97 111]
a > b: [False  True False]
a >= b: [False  True False]
a < b: [ True False  True]
a <= b: [ True False  True]


#How to Check Whether Specified Values are Present in NumPy Array?

In [11]:
#using NumPy's Vectorized Comparison
arr = np.array([[2, 3, 0],
                [4, 1, 6]])
val=6
p=np.any(arr==val)
print(p)

True


In [12]:
#Using NumPy isin() for Multiple Values
arr = np.array([[2, 3, 0],
                [4, 1, 6]])
vals=[0,4,60]
ans={v:bool(np.isin(v,arr)) for v in vals}
print(ans)

{0: True, 4: True, 60: False}


In [13]:
#Using in Operator
arr = np.array([[2, 3, 0],
                [4, 1, 6]])

print(2 in arr)
print(10 in arr)

True
False


In [14]:
#Using Flattening and Python Membership
arr = np.array([[2, 3, 0],
                [4, 1, 6]])
v=3
out=v in arr.ravel() # flattening array
print(out)

True


How to get all 2D diagonals of a 3D NumPy array

In [15]:
#you can extract 2D diagonals from each sub-array of a
#3D array using numpy.diagonal() function.

#np.diagonal(a, axis1, axis2)
# Create a 3D numpy array of shape (3, 4, 4)
arr = np.arange(3 * 4 * 4).reshape(3, 4, 4)
print("Original 3D array:\n", arr)

# Extract diagonals from each 2D sub-array
diag_arr = np.diagonal(arr, axis1=1, axis2=2)
print("\n2D diagonal array:\n", diag_arr)

Original 3D array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]

2D diagonal array:
 [[ 0  5 10 15]
 [16 21 26 31]
 [32 37 42 47]]


FLATTEN A MATRIX

In [17]:
matrix = np.array([[10, 20, 30], [40, 50, 60]])
flat = matrix.flatten()
print(flat)

'''Parameters:
order='C' Flatten in row-major order (default).
order='F' Flatten in column-major order.
order='A' Flatten in column-major if memory is Fortran-contiguous, else row-major.
order='K' Flatten in the order elements occur in memory.
'''

[10 20 30 40 50 60]


"Parameters:\norder='C' Flatten in row-major order (default).\norder='F' Flatten in column-major order.\norder='A' Flatten in column-major if memory is Fortran-contiguous, else row-major.\norder='K' Flatten in the order elements occur in memory.\n"

Flatten a 2D Numpy Array into 1D Array

In [18]:
#USING NP.RAVEL()
a = np.array([[1, 2, 3], [4, 5, 6]])
res = a.ravel()
print(res)

[1 2 3 4 5 6]


In [19]:
#Using np.ndarray.flatten()
a = np.array([[1, 2, 3], [4, 5, 6]])
res = a.flatten()
print(res)

[1 2 3 4 5 6]


In [21]:
#using reshape(-1)-> coverts array in 1 d
#The -1 tells NumPy to automatically compute the required length.
a = np.array([[1, 2, 3], [4, 5, 6]])
res = a.reshape(-1)
print(res)

[1 2 3 4 5 6]


In [24]:
#using concatenate-> it convat each array one by one forming 1D array
res=np.concatenate(a)
print(res)

[1 2 3 4 5 6]


REVERSE AN ARRAY

In [40]:
#USING SLICING
#USING NP.FLIP()
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
res1=np.flip(arr)

print(res1)
for r in res1:
  for i in range(len(r)//2):
    r[i],r[arr.shape[1]-1-i]=r[arr.shape[1]-1-i],r[i]

print(res1)


[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


2